Content update
OpenLiberty/guide-microshed-testing pull request #87
Opened 2021-06-18 14:18 UTC by rutavshah

2021-07-08 19:07 UTC, AustinSeto requested changes
Just some minor suggestions for the README content.

Other than that, the static version of the guide looks guide, instructions and app all work.

2021-07-08 19:07 UTC, AustinSeto commented on README.adoc
> +Sometimes tests might pass in development and testing (dev/test) environments,
"testing (dev/test)" seems redundant, can we just say "testing environments"?

2021-07-08 19:07 UTC, AustinSeto commented on README.adoc
> +In this case, you're using the default application readiness check at the http://localhost:9080/health/ready[http://localhost:9080/health/ready^] URL, which is enabled by the [hotspot=mpHealth file=1
Update `MicroProfile Health` to `mpHealth-3.0`

2021-07-12 13:07 UTC, gkwan-ibm commented on README.adoc
> +In this case, you're using the default application readiness check at the http://localhost:9080/health/ready[http://localhost:9080/health/ready^] URL, which is enabled by the [hotspot=mpHealth file=1
No need to update at here because not want to hard code the version 3.0

2021-07-12 13:12 UTC, gkwan-ibm commented on README.adoc
> +Sometimes tests might pass in development and testing (dev/test) environments,
Let ID to review. Line 38 is using dev/test.

2021-07-14 13:20 UTC, Rwalls1 reviewed
The updates look good, I just have a few comments.

2021-07-14 13:20 UTC, Rwalls1 commented on README.adoc
> +but fail in production because the application is running differently in production than it's in dev/test.
Change "is running differently" to "runs differently". Also, change "than it's in dev/test" to "than in dev/test".

2021-07-14 13:20 UTC, Rwalls1 commented on README.adoc
> +Fortunately, you can minimize these parity issues between development and production
Change "parity issues" to "differences". Also, change "development" to "dev/test" to maintain consistency.

2021-07-14 13:20 UTC, Rwalls1 commented on README.adoc
> +This command might take some time to run the first time because the dependencies and the Docker image for Open Liberty must download.
Change "the first time" to "initially" to be more concise.

2021-07-14 13:20 UTC, Rwalls1 commented on README.adoc
>  an already running Open Liberty server. Run the following Maven goal to start Open Liberty in development mode:
Change "on an already running Open Liberty server" to "on an active Open Liberty server" to be more concise.

2021-07-14 13:20 UTC, Rwalls1 commented on README.adoc
> +The `PersonServiceIT` class outlines some basic information that informs how MicroShed Testing starts the application runtime and at which URL path the application will be available:
Change "at which URL path the application will be available:" to "at which URL path the application is available".

2021-07-14 13:20 UTC, Rwalls1 commented on README.adoc
> +In this case, you're using the default application readiness check at the http://localhost:9080/health/ready[http://localhost:9080/health/ready^] URL, which is enabled by the [hotspot=mpHealth file=1
Add an identifying noun after "HTTP 200" to indicate what is being referred to, so change to something like "the HTTP 200 message".

2021-07-14 13:20 UTC, Rwalls1 commented on README.adoc
> +Import the [hotspot=importMPApp file=0]`ApplicationContainer` class and the [hotspot=importContainer file=0]`Container` annotation, create the [hotspot=mpApp file=0]`ApplicationContainer` application
Add an identifying noun after "[hotspot=container file=0]`@Container`" to clarify what's being referred to, so change to something like "the [hotspot=container file=0]`@Container` annotation".

2021-07-14 13:20 UTC, Rwalls1 commented on README.adoc
> +that is running at `\http://localhost:9080/guide-microshed-testing/people`,
Add an identifying noun after "`\http://localhost:9080/guide-microshed-testing/people`".

2021-07-15 13:34 UTC, Rwalls1 approved these changes
The latest updates look good.

2021-07-15 14:03 UTC, AustinSeto approved these changes
No comment from ID on "dev/test" wording, so I'll approve

2021-07-15 18:26 UTC, gkwan-ibm approved these changes

2021-07-15 18:26 UTC, merged