Restructure update
OpenLiberty/guide-microshed-testing pull request #96
Opened 2021-11-04 22:05 UTC by davidwyao

Address #86

2021-11-05 16:59 UTC, gkwan-ibm requested changes
@davidwyao 
- test failed
- and I still want the hotspots work in following paragraphs:
> Remove the container code from the PersonServiceIT class. Remove import statements for ApplicationContainer and Container, and the ApplicationContainer app field. Next, annotate the PersonServiceIT class with the @SharedContainerConfig annotation that references the AppDeploymentConfig shared configuration class.

and

> Similarly, replace the ErrorPathIT class to remove the container code. Remove import statements for ApplicationContainer and Container, and the ApplicationContainer app field. Next, annotate the ErrorPathIT class with the @SharedContainerConfig annotation.

2021-11-11 20:05 UTC, gkwan-ibm commented
hi @davidwyao 

- **Writing your first test**
  - Why need to change this section? Would you revert it?
- **Sharing configuration across multiple classes**
  - create subsections to make things clear as following:

>**Creating common configuration**
>
>To solve this issue...
>...

> **Updating the PersonServiceIT class**
>
>Remove the container code from the `PersonServiceIT` class. ...
>...

> **Updating the ErrorPathIT class**
>
>Similarly, replace the `ErrorPathIT` class
>...

2021-11-11 20:17 UTC, davidwyao commented
> hi @davidwyao
> 
> * **Writing your first test**
>   
>   * Why need to change this section? Would you revert it?
> * **Sharing configuration across multiple classes**
>   
>   * create subsections to make things clear as following:
> 
> > **Creating common configuration**
> > To solve this issue...
> > ...
> 
> > **Updating the PersonServiceIT class**
> > Remove the container code from the `PersonServiceIT` class. ...
> > ...
> 
> > **Updating the ErrorPathIT class**
> > Similarly, replace the `ErrorPathIT` class
> > ...

The **Writing your first test** section included two incremental updates to `PersonServiceIT`, the second of which simply added more tests to be run again the same way as the first.

2021-12-15 21:16 UTC, Kevcpro approved these changes

2021-12-16 15:46 UTC, gkwan-ibm approved these changes

2021-12-16 15:46 UTC, merged